### ISSUE TITLE
外部サーバに建てたnekostoreのcollectionに対する操作でtimeout発生

### ISSUE THREAD

**Issue by HillTopTRPG** [esnya/nekostore#5]
素晴らしいプログラムをありがとうございます。
いつも大変お世話になっています。

クライアントの向き先をローカルサーバから外部サーバにするとtimeoutが発生するようになります。
調査に必要な情報があれば教えてください。

サーバ
```
import BasicDriver from "nekostore/lib/driver/basic";
import SocketDriverServer from "nekostore/lib/driver/socket/SocketDriverServer";

async function main(): Promise<void> {
  try {
    const driver = new BasicDriver();
    const io = require('socket.io').listen(8000);

    console.log("Quoridorn Server is Ready.");

    io.on("connection", (socket: any) => {
      console.log("Connected", socket.id);

      socket.on('disconnect', () => {
        console.log('disconnected', socket.id);
      });

      // nekostore起動！
      new SocketDriverServer(driver, socket);
    });
  } catch (err) {
    console.error(err);
  }
}
main();
```

クライアント
```
import Nekostore from "nekostore";
import SocketDriver from "nekostore/lib/driver/socket";
import * as Socket from 'socket.io-client';

/**
 * どどんとふ公式鯖に建ててもらったQuoridorn用テスト環境
 * 有効な静的ファイルに対するアクセス以外は全て8000番ポートにリダイレクトする設定
 */
const host = "ws://quori-dev.onlinesession.app";
// const port = 8000;

interface Data {
  foo: string;
  bar?: number;
}

async function test_client(): Promise<void> {
  const socket = Socket.connect(`http://${host}`);

  const driver = new SocketDriver({ socket });
  const nekostore = new Nekostore(driver);

  console.log("Go Go Go!!!");

  const c1Ref = nekostore.collection<Data>("c1");
  
  // collectionに対する何らかの関数を呼ぶとエラー
  c1Ref.add({
    foo: "Hello World."
  });
}

test_client().then(() => {}, err => {
  console.error(err.stack);
  process.exit(err);
});
```

クライアントコンソール
```
Go Go Go!!!
(node:18476) UnhandledPromiseRejectionWarning: Error: collectionAdd timed out 7fd89343-913e-497c-b777-daf0832500fd
    at Timeout.setTimeout (C:\dev\quoridorn-server\node_modules\nekostore\src\driver\socket\SocketDriver.ts:69:11)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
(node:18476) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:18476) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

サーバコンソール
```
Quoridorn Server is Ready.
Connected yfCuUoW1OPPtYMYSAAAA
```

**Comment by HillTopTRPG** [comment]
自己解決いたしました！
クライアント側がダメでした。

原因
* スキーム名は `ws` ではなく `wss` が正しかった
* 変数 host にスキーム名も入れてしまっていた
* そもそもSocket接続すらできてない状態だったのでissue上げるほどのことではなかった
* timeoutオプションがデフォルトの1000msでは短かったので、長くした

お騒がせしましたっ（土下座
```
import Nekostore from "nekostore";
import SocketDriver from "nekostore/lib/driver/socket";
import * as Socket from 'socket.io-client';
import QuerySnapshot from "nekostore/lib/QuerySnapshot";

// const scheme = "http";
const scheme = "wss";

// const host = "127.0.0.1";
const host = "quori-dev.onlinesession.app";

// const port = 8000;

interface Data {
  foo: string;
  bar?: number;
}

async function test_client(): Promise<void> {
  const socket = Socket.connect(`${scheme}://${host}`); // :${port}

  socket.on("connect", () => {
    console.log("connected");
  });

  socket.on("connect_timeout", () => {
    console.log("connect_timeout");
  });

  socket.on("connect_error", (err) => {
    console.log("connect_error", err);
  });

  const driver = new SocketDriver({ socket, timeout: 5000 });
  const nekostore = new Nekostore(driver);

  console.log("Go Go Go!!!");

  const c1Ref = nekostore.collection<Data>("c1");

  c1Ref.onSnapshot((snapshot: QuerySnapshot<Data>) => {
    snapshot.docs.forEach(async doc => {
      const docSnapshot = await doc.ref.get();
      if (docSnapshot.exists()) {
        console.log(doc.data);
      }
    });
  });

  // collectionに対する何らかの関数を呼ぶとエラー
  c1Ref.add({
    foo: "Hello World."
  });
}

test_client().then(() => {}, err => {
  console.error(err.stack);
  process.exit(err);
});
```
